plugins:
  - jekyll-environment-variables
logo:
  mobile: /images/club_logo.png
  mobile_height: 32px
  mobile_width: 32px
  desktop: /images/logo.png
  desktop_height: 32px
  desktop_width: 176px
permalink: pretty
sass:
  style: compressed
url: https://fda-mhs.github.io
remote_theme: zerostaticthemes/jekyll-serif-theme
defaults:
  - scope:
      path: ""
      type: events
    values:
      layout: event
  - scope:
      path: ""
      type: members
    values:
      layout: member
collections:
  events:
    output: true
  members:
    output: true
title: FDA MHS
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
baseurl: /
home:
  limit_events: 6
